apiVersion: apps/v1
kind: Deployment
metadata:
  name: crops-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crops
  template:
    metadata:
      labels:
        app: crops
    spec:
      containers:
        - name: crops
          image: us.gcr.io/epitome-trade/crops
          env:
            - name: MONGO_URI
              value: 'mongodb://crops-mongo-srv:27017/crops'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: crops-srv
spec:
  selector:
    app: crops
  ports:
    - name: crops
      protocol: TCP
      port: 3000
      targetPort: 3000